"""add_is_deleted_field_to_documents

Revision ID: 05826d683e8e
Revises: c6ab08228bdd
Create Date: 2025-07-13 17:20:32.701136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05826d683e8e'
down_revision: Union[str, None] = 'c6ab08228bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column with default value False for SQLite compatibility
    op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), nullable=False, default=False, server_default='0'))
    
    # Update existing records to set the value explicitly (in case needed)
    op.execute("UPDATE documents SET is_deleted = 0 WHERE is_deleted IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_deleted')
    # ### end Alembic commands ###
